sonar.projectKey=PanaderiaSaborArtesano
sonar.projectName=Panadería El Sabor Artesano - Backend
sonar.sources=src/
sonar.tests=tests/
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**
sonar.coverage.exclusions=**/*.test.*,tests/**
sonar.test.inclusions=tests/**/*.test.js
host.url=http://localhost:9000
sonar.token=sqp_d0153ee5196c92725a440a93449b6bad03d4c71d