sonar.projectKey=Panaderia
sonar.projectName=Panaderia
sonar.sources=src/
sonar.tests=tests/
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,src/index.js,src/server.js,src/loaders/menuHandler.js,src/routes/authRoutes.js,src/services/authService.js,src/middlewares/requestLogger.js
sonar.coverage.exclusions=**/*.test.*,tests/**,src/index.js,src/server.js,src/loaders/middlewareHandler.js,src/routes/authRoutes.js,src/services/authService.js,src/middlewares/requestLogger.js
sonar.test.inclusions=tests/**/*.test.js
sonar.host.url=http://localhost:9000
sonar.login=sqp_802baae98514fffaeabc4467767d828f3fcf15c0